// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bknicolrzrkxwqxbwflk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbmljb2xyenJreHdxeGJ3ZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjAzMzAsImV4cCI6MjA2NjQ5NjMzMH0.aF7GAoH5udXbvVEXFeUBeaKbdCP4XzGh8PU66AF5vCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);